version: '2.1'
services:

  neo4j:
        image: neo4j:latest
        container_name: neo4j
        restart: always
        ports:
          - "7474:7474"
          - "7687:7687"
        environment:
          TZ: Asia/Shanghai
        volumes:
          - /opt/infrastructure/volumes/neo4j/data:/data